### ISSUE TITLE
Logic: hiding rows and auto-selecting values

### ISSUE THREAD

**Issue by jf1** [robinheydon/ceat#1]
Virtually all the logic enhancements can be triggered when the type of cycling infra is selected:
Path: 	hide PCU, speed; show 1or2w & width @ shared-use 2-way
Road:	hide barriers, peds (set to <100), 1or2w & width (set to High+)
ACL/MCL:	hide barriers, peds (set to <100), 1or2w; show width @ ACL/MCL
Light P:	hide barriers, peds (set to <100); show 1or2w @ 1way, width @ cycleway-1
Full P:	hide barriers, PCU, speed, peds (set to <100); show 1or2w @ 1way, width @ cycleway-1

The only other trigger would happen if a user changed the "1-way or 2-way" option
1or2w:	only shown if infra=Path/Light/Full; onchange, width swaps between cycleway-1 & -2

Light and Full just need "1-way" and "2-way" but Path would benefit from 3 options:
Segregated 1-way; Segregated 2-way; Shared-use 2-way.
If Infra=Path then both segregated options should automatically set peds=0 too.

I've hidden Directness for now - it'll only be apt if someone's scoring a proposed route, and even then it might be possible to compute it.

**Comment by robinheydon** [comment]
I've done the line hiding - I think there is still a few side effects which need fixing.

I've not done anything more radical at this time.

**Comment by jf1** [comment]
Thanks. Are you aware of http://ceat.cyclenation.org.uk/next/ and should I
try to set it up as a github fork, branch or something else?

**Comment by jf1** [comment]
The line hiding seems to work as expected [here](http://www.robinheydon.net/ceat/) but those changes are no longer in github since [/next](http://ceat.cyclenation.org.uk/next/) was merged in.

One bug in http://www.robinheydon.net/ceat/ is: when `infra=road` the width buttons are hidden but the width value is only `High` when it should be `High+`.

If `Access Barriers` will be moved to the junctions tool then it could be removed from here altogether, however I feel it'll be more reassuring for users if it's left in here until the junctions tool is developed. Ideally the line will be hidden when anything other than infra=path is selected, and its value will always be detached from the effectiveness rating calculations (or fixed as High+ if that's easier).

`Directness` could be treated similarly - visible and click-able but detached from the effectiveness rating calculations, or fixed to `High+`.

Hiding the extra `Width` lines could be achieved in one of two ways: keep the `Sub-standard  Minimum  Compromised  Efficient  Future-proof` row and below it show the appropriate row for the current `infra` and `1-way/2-way/shared` selections; or just have one row of double-height buttons that initially display just the words then once `infra` and `1-way/2-way/shared` have been selected each button gets words and values, eg:
![image](https://cloud.githubusercontent.com/assets/4711363/15229294/4a4374d4-1888-11e6-9d80-7463e0f44899.png)

My preference would be one set of double-height buttons but at this stage whatever's simplest to implement is most apt, and leaving it as-is wouldn't be too troublesome (it helps people see all the options, but the presentation isn't as simple as it could be).

`Social Safety (day)` has straightforward logic: it's another factor for the `effectiveness_rating` with `fine` = `High+` and `uncomfortable` = `Med`.

`Night-time Safety` does not need to be implemented at this stage but it's useful to keep the place-holder line there. If you are able to implement it then we'll need a separate `night_score` output - I envisage a line under the main score of eg [Night-time score: X] that has no extra description and isn't shown at all if `night_score` = `day_score`. `locked` = `FAIL` and the other values range from `Low` to High+`.

**Comment by robinheydon** [comment]
Ok, I'll fix : One bug in http://www.robinheydon.net/ceat/ is: when infra=road the width buttons are hidden but the width value is only High when it should be High+.
