### ISSUE TITLE
overall_score idea to get more 1/5 results

### ISSUE THREAD

**Issue by jf1** [robinheydon/ceat#2]
Currently it's hard to get 1/5 - 0/5 or 2/5 are much more likely.
The /next version has this array:
var overall_scores = {
	0: [0, 0, 0, 0, 0],
	1: [0, 1, 2, 2, 2],
	2: [0, 2, 3, 3, 3],
	3: [0, 2, 3, 4, 4],
	4: [0, 2, 3, 4, 5]
};
This can be described with a 3x3 grid (ignoring the Low- or High+ values) plus: Score = 0 if either factor can’t achieve a Low rating; or Score = 5 if both factors are rated better than High.

A new idea would be to have:
Score = 1 if one Effectiveness factor is Low- or the Separation rating is 1 below Low
Score = 0 if one Effectiveness factor is Low- and the Separation rating is 1 below Low
Score = 0 if two or more Effectiveness factors are Low- or the Separation rating is 2 below Low

This would require an 'array' of:
	0: [0, 0, E, E, E],
	1: [0, 1, 2, 2, 2],
	2: [M, 2, 3, 3, 3],
	3: [M, 2, 3, 4, 4],
	4: [M, 2, 3, 4, 5]
Where:
E=0 if 2 or more Effectiveness inputs are Low-, or E=1 if only one Effectiveness inputs is Low-, and
M=0 if Separation rating is one below requirement for Low-, or M=1 if Separation rating just reaches Low-

This doesn't change much policy-wise as we're not that bothered about scores below 2 but it would make the tool appear more responsive to the inputs so could help people 'buy in' to it.

**Comment by robinheydon** [comment]
I've committed some new code that attempts to address this. However, I was a little confused about the M=0 requirement. Please have a play with the scoring and see what it is like,

**Comment by jf1** [comment]
This line:

> M=0 if Separation rating is one below requirement for Low-, or M=1 if Separation rating just reaches Low-

Could be clearer, as:
M=0 if infra is two levels below the requirement for a Low separation rating, or M=1 if infra is one level below the requirement for a Low separation rating.

**Comment by jf1** [comment]
Another way to describe this, in three stages:

if infra is two levels below the requirement for Low then `separation_rating=FAIL` and `score=0`

else if two or more Effectiveness inputs are Low- or one is Low-- then `effectiveness_rating=FAIL` and `score=0`

else get score from this array:
0: [0, 0, 1, 1, 1],
1: [0, 1, 2, 2, 2],
2: [1, 2, 3, 3, 3],
3: [1, 2, 3, 4, 4],
4: [1, 2, 3, 4, 5]

**Comment by robinheydon** [comment]
ok, I'll interpret that as:

get the score from the updated array

if the score is 1 and two infra-levels are Low- then score = 0

if the score is 1 and one infra-levels are FAIL then score = 0

**Comment by jf1** [comment]
Ish. Try...

get the score from the updated array

if the score is 1 and infra type is two levels below that required for Low
then score = 0 (infra FAIL)

if the score is 1 and two effectiveness factors are Low- then score = 0
(effectiveness FAIL)
